name: amplify_trips_planner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_api: ^0.6.12
  amplify_auth_cognito: ^0.6.12
  amplify_authenticator: ^0.2.4
  amplify_datastore: ^0.6.12
  amplify_flutter: ^0.6.12
  amplify_storage_s3: ^0.6.12
  intl: ^0.17.0
  get: ^4.6.5
  routes_lib:
    path: libraries/routes_lib

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
